CREATE TABLE blocks (
    id SERIAL PRIMARY KEY,
    author TEXT,
    difficulty BIGINT,
    extra_data BYTEA,
    gas_limit BIGINT,
    gas_used BIGINT,
    hash BYTEA,
    logs_bloom BYTEA,
    miner TEXT,
    mix_hash BYTEA,
    nonce BYTEA,
    number BIGINT,
    parent_hash BYTEA,
    receipts_root BYTEA,
    sha3_uncles BYTEA,
    size BIGINT,
    state_root BYTEA,
    total_difficulty NUMERIC,
    timestamp BIGINT,
    base_fee_per_gas BIGINT,
    transactions BYTEA[],
    transactions_root BYTEA,
    uncles BYTEA[],
    withdrawals BYTEA[], -- Si les retraits sont des objets complexes, vous devrez peut-être ajuster ce type
    withdrawals_root BYTEA,
    blob_gas_used BIGINT,
    excess_blob_gas BIGINT,
    parent_beacon_block_root BYTEA
);
